version: '3'

services:
  db:
    image: mysql:8.0
    container_name: fusalmo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sitio_licencias_lis
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USER:-root}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/init-db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"  # Cambiado de "3306:3306" a "3307:3306"
    networks:
      - fusalmo-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fusalmo-backend
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      # Sobreescribe la variable para que apunte al servicio de base de datos
      - HOSTNAME=db
    networks:
      - fusalmo-network
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fusalmo-frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fusalmo-network
    restart: unless-stopped
    environment:
      - API_URL=http://backend:8080

networks:
  fusalmo-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local